#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd
#!/bin/bash
: '
created by learning
gokul
on 27.7.18
'
ls -a 
pwd

